project:
  type: website
  output-dir: docs

website:
  title: "R. Daniel Jonsson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: writings.qmd
        text: Writings
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true